services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./university.db:/app/university.db
    environment:
      - PYTHONUNBUFFERED=1
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web