FROM nginx:alpine

# کپی فایل‌های HTML و JavaScript
COPY index.html /usr/share/nginx/html/
COPY login.html /usr/share/nginx/html/
COPY students.html /usr/share/nginx/html/
COPY teachers.html /usr/share/nginx/html/
COPY courses.html /usr/share/nginx/html/
COPY reports.html /usr/share/nginx/html/
COPY repo.js /usr/share/nginx/html/

# تنظیمات Nginx
COPY nginx.conf /etc/nginx/nginx.conf
